"""add scan error message

Revision ID: f19df689ebd6
Revises: fc183ab5f8f7
Create Date: 2026-08-21 19:32:17.992209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19df689ebd6'
down_revision: Union[str, Sequence[str], None] = 'fc183ab5f8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'error_message')
    # ### end Alembic commands ###
